# Generated by Django 3.2.6 on 2021-08-31 08:08

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('ip_adresa', models.CharField(blank=True, max_length=14, null=True, verbose_name='IP adresa')),
                ('jmeno', models.CharField(blank=True, max_length=350, null=True, verbose_name='Jméno')),
                ('eui', models.CharField(blank=True, max_length=50, null=True, verbose_name='Gateway EUI')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Port')),
                ('povolena', models.BooleanField(default=True, verbose_name='Povolena')),
            ],
            options={
                'verbose_name': 'Gateway',
                'verbose_name_plural': 'Gateways',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Zprava',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id_zpravy', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID zprávy')),
                ('verze', models.PositiveIntegerField(blank=True, null=True, verbose_name='Verze')),
                ('token', models.CharField(blank=True, max_length=128, null=True, verbose_name='Token')),
                ('payload', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Payload')),
                ('ip_adresa', models.CharField(blank=True, max_length=14, null=True, verbose_name='IP adresa')),
                ('port', models.PositiveIntegerField(blank=True, null=True, verbose_name='Port')),
                ('smer', models.CharField(blank=True, choices=[('TX', 'TX - Odeslána'), ('RX', 'RX - Přijata')], max_length=2, null=True, verbose_name='Směr zprávy')),
            ],
            options={
                'verbose_name': 'Zpráva',
                'verbose_name_plural': 'Zprávy',
                'ordering': ('-created',),
            },
        ),
    ]
