# Generated by Django 3.2.6 on 2021-09-04 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_zprava_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprava',
            name='mic',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='MIC'),
        ),
    ]
