# Generated by Django 3.2.6 on 2021-09-04 18:06

from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_zprava_mic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zarizeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(blank=True, max_length=128, null=True, verbose_name='Název')),
                ('trida', models.CharField(blank=True, max_length=128, null=True, verbose_name='Třída')),
                ('devaddr', models.PositiveIntegerField(blank=True, null=True, verbose_name='DevAddr')),
                ('deveui', models.PositiveIntegerField(blank=True, null=True, verbose_name='DevEUI')),
                ('otaa', models.BooleanField(default=False, verbose_name='OTAAA')),
                ('appeui', models.PositiveIntegerField(blank=True, null=True, verbose_name='AppEUI')),
                ('nwkskey', models.PositiveIntegerField(blank=True, null=True, verbose_name='NwkSKey')),
                ('appskey', models.PositiveIntegerField(blank=True, null=True, verbose_name='AppSKey')),
                ('tx_kanal', models.PositiveIntegerField(blank=True, null=True, verbose_name='Kanál')),
                ('tx_datr', models.CharField(blank=True, max_length=128, null=True, verbose_name='Data rate')),
            ],
            options={
                'verbose_name': 'Zařízení',
                'verbose_name_plural': 'Zařízení',
                'ordering': ('-created',),
            },
        ),
    ]
