# Generated by Django 3.2.6 on 2021-09-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_zarizeni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zarizeni',
            name='appeui',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='AppEUI'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='appskey',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='AppSKey'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='devaddr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='DevAddr'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='deveui',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='DevEUI'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='nwkskey',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='NwkSKey'),
        ),
    ]
