# Generated by Django 3.2.6 on 2021-09-09 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20210904_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprava',
            name='zarizeni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zpravy', to='monitoring.zarizeni', verbose_name='Zarizeni'),
        ),
    ]
