# Generated by Django 3.2.6 on 2021-09-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_zprava_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprava',
            name='hex_data',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='HEX Data'),
        ),
    ]
