# Generated by Django 3.2.6 on 2021-10-01 08:11

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_zprava_hex_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('stav_kontaktu', models.BooleanField(verbose_name='Stav kontaktu')),
                ('teplota', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Teplota')),
                ('napeti_baterie', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Napětí baterie')),
                ('zprava', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_hodnoty', to='monitoring.zprava', verbose_name='data_hodnoty')),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ('-created',),
            },
        ),
    ]
