# Generated by Django 3.2.6 on 2021-10-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='zarizeni',
            name='povoleno',
            field=models.BooleanField(default=True, verbose_name='Povoleno'),
        ),
    ]
