# Generated by Django 3.2.7 on 2021-10-08 12:52

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_zarizeni_povoleno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zabbix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nazev', models.CharField(blank=True, max_length=128, null=True, verbose_name='Název')),
                ('ip_adresa', models.CharField(max_length=14, verbose_name='IP adresa')),
                ('port', models.PositiveIntegerField(default='10051', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(65535)], verbose_name='Port')),
                ('povolen', models.BooleanField(default=True, verbose_name='Povolena')),
                ('zarizeni', models.ManyToManyField(related_name='zarizeni', to='monitoring.Zarizeni')),
            ],
            options={
                'verbose_name': 'Zabbix',
                'verbose_name_plural': 'Zabbix',
                'ordering': ('-created',),
            },
        ),
    ]
