# Generated by Django 3.2.7 on 2021-10-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_zabbix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='napeti_baterie',
        ),
        migrations.RemoveField(
            model_name='data',
            name='stav_kontaktu',
        ),
        migrations.RemoveField(
            model_name='data',
            name='teplota',
        ),
        migrations.AddField(
            model_name='data',
            name='hodnota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Hodnota'),
        ),
        migrations.AddField(
            model_name='data',
            name='jednotka',
            field=models.CharField(blank=True, choices=[('VOLTY', 'V'), ('STUPNE', '°C'), ('BEZ_JEDNOTKY', '')], max_length=20, null=True, verbose_name='Jednotka'),
        ),
        migrations.AddField(
            model_name='data',
            name='typ_hodnoty',
            field=models.CharField(blank=True, choices=[('NAPETI', 'Napětí'), ('TEPLOTA', 'Teplota'), ('STAV_KONTAKTU', 'Stav kontaktu')], max_length=20, null=True, verbose_name='Typ hodnoty'),
        ),
        migrations.AddField(
            model_name='data',
            name='zarizeni',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_hodnoty', to='monitoring.zarizeni', verbose_name='data_hodnoty'),
        ),
        migrations.AlterField(
            model_name='zabbix',
            name='povolen',
            field=models.BooleanField(default=True, verbose_name='Povolen'),
        ),
    ]
