# Generated by Django 3.2.7 on 2021-10-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0016_auto_20211014_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='zprava',
            name='devaddr',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Adresa zařízení'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='fcnt',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='FCnt'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='fctrl',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='FCtrl'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='fhdr',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='FHDR'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='fopts',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='FOpts'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='fport',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='FPort'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='frm_payload',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='FRM payload'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='mac_payload',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='MAC Payload'),
        ),
        migrations.AddField(
            model_name='zprava',
            name='mhdr',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='MHDR'),
        ),
        migrations.AlterField(
            model_name='zprava',
            name='mic',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='MIC'),
        ),
    ]
