# Generated by Django 3.2.7 on 2021-10-27 14:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0017_auto_20211027_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZabbixSenderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('odeslano', models.BooleanField(default=True, verbose_name='Odesláno')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_log', to='monitoring.data')),
                ('zabbix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_log', to='monitoring.zabbix')),
            ],
            options={
                'verbose_name': 'ZabbixSender log',
                'verbose_name_plural': 'ZabbixSender logy',
                'ordering': ('-created',),
            },
        ),
    ]
