# Generated by Django 3.2.7 on 2021-10-29 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0018_zabbixsenderlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zprava',
            old_name='typ_zpravy',
            new_name='typ_zpravy_GWMP',
        ),
        migrations.AddField(
            model_name='zprava',
            name='typ_zpravy_MAC',
            field=models.IntegerField(blank=True, choices=[(0, 'Join request'), (1, 'Join accept'), (2, 'Unconfirmed data UP'), (3, 'Unconfirmed data DOWN'), (4, 'Confirmed data UP'), (5, 'Confirmed data DOWN'), (7, 'Proprietary')], null=True, verbose_name='Typ zprávy MAC Message'),
        ),
    ]
