# Generated by Django 3.2.7 on 2022-02-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0019_auto_20211029_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='eui',
            field=models.CharField(max_length=50, unique=True, verbose_name='Gateway EUI'),
        ),
        migrations.AlterField(
            model_name='gateway',
            name='nazev',
            field=models.CharField(max_length=350, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='appskey',
            field=models.CharField(max_length=128, verbose_name='AppSKey'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='devaddr',
            field=models.CharField(max_length=128, verbose_name='DevAddr'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='deveui',
            field=models.CharField(max_length=128, unique=True, verbose_name='DevEUI'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='nazev',
            field=models.CharField(max_length=128, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='zarizeni',
            name='nwkskey',
            field=models.CharField(max_length=128, verbose_name='NwkSKey'),
        ),
        migrations.AlterField(
            model_name='zprava',
            name='typ_zpravy_GWMP',
            field=models.IntegerField(blank=True, choices=[(0, 'Push data'), (1, 'Push acknowledge'), (2, 'Pull data'), (3, 'Pull response'), (4, 'Pull acknowledge')], null=True, verbose_name='Typ zprávy GWMP'),
        ),
    ]
